var PostConstants = {
  RECEIVE_POSTS: "RECEIVE_POSTS",
  RECEIVE_SUB_POSTS: "RECEIVE_SUB_POSTS",
  RECEIVE_POST: "RECEIVE_POST",
  RECEIVE_COMMENT: "RECEIVE_COMMENT"
};

module.exports = PostConstants;
